### ISSUE TITLE
Crashing with mods..

### ISSUE THREAD

**Issue by Run0ver** [Fexcraft/TimePays#1]
Hello I've been using fsmm and states, the TimePays has compitablity issues which casue the server to pause and not starting when I kill the server, the outlog of a crash the cause of TimePays.
Forge version 1.12.2 2838 

here is the link for the entire logs https://pastebin.com/L9HcHhZw

**Comment by Fexcraft** [comment]
Is there a ``tpm_rewards.json`` file in the config folder?
If the contents is `{}` try setting it to `[]` and save.

**Comment by Run0ver** [comment]
yes that did fix the problem. from {} to [] the tpm_rewards.json is empty is that normal or should I type the rewards by myself?

**Comment by Fexcraft** [comment]
Yes, you'll have to setup some rewards.
I'll upload a fixed version of this mod in a few minutes so this crash shouldn't happen again.
It was because it generated the file with the wrong brackets.

**Comment by Fexcraft** [comment]
There are examples on the main page of this repository on how to make rewards.

**Comment by Run0ver** [comment]
got it thank you :)!
